# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BadgerCli < Formula
  desc ""
  homepage "https://github.com/lovromazgon/homebrew-tap"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/lovromazgon/badger-cli/releases/download/v0.2.0/badger-cli_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "fe36f45c2e25a5a6b97a21f4f6c618161e753f0ca0be12f9c2c34ea0b987f8f9"

      def install
        bin.install "badger-cli"
      end
    end
    on_arm do
      url "https://github.com/lovromazgon/badger-cli/releases/download/v0.2.0/badger-cli_0.2.0_Darwin_arm64.tar.gz"
      sha256 "7bc9818117c24d97b995be3dc01c6b6560d07664c623dcdb6ae7dd1ba31f9a49"

      def install
        bin.install "badger-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lovromazgon/badger-cli/releases/download/v0.2.0/badger-cli_0.2.0_Linux_x86_64.tar.gz"
        sha256 "8892f037d234b091ebb08234683c4790720aefb2a2442da0d5af96aead6298d4"

        def install
          bin.install "badger-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lovromazgon/badger-cli/releases/download/v0.2.0/badger-cli_0.2.0_Linux_arm64.tar.gz"
        sha256 "b89a0b95f9b14a6538f36518fd369e2044b4c51e7084349edad86008fef93bde"

        def install
          bin.install "badger-cli"
        end
      end
    end
  end
end
