# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BadgerCli < Formula
  desc ""
  homepage "https://github.com/lovromazgon/homebrew-tap"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/lovromazgon/badger-cli/releases/download/v0.1.1/badger-cli_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "4fb71a051175774a8a1fdb4e92dcb276256067aad6b7365a5d6a2bf7ab597ade"

      def install
        bin.install "badger-cli"
      end
    end
    on_arm do
      url "https://github.com/lovromazgon/badger-cli/releases/download/v0.1.1/badger-cli_0.1.1_Darwin_arm64.tar.gz"
      sha256 "66e81a85fa88e8bf595e7bd97d3330436e8425c2ec4871ff852b3c1060b2ec88"

      def install
        bin.install "badger-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lovromazgon/badger-cli/releases/download/v0.1.1/badger-cli_0.1.1_Linux_x86_64.tar.gz"
        sha256 "838bf68fc1209d1553a311ca3ee92cf66b91579d85a18b16fa9de436f66b1d1d"

        def install
          bin.install "badger-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lovromazgon/badger-cli/releases/download/v0.1.1/badger-cli_0.1.1_Linux_arm64.tar.gz"
        sha256 "c7b8c6cdc0fb91225813aaeb3ce52f12c880626a9e3da42c5fe6d86e94679361"

        def install
          bin.install "badger-cli"
        end
      end
    end
  end
end
