# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaTui < Formula
  desc ""
  homepage "https://github.com/lovromazgon/homebrew-tap"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lovromazgon/grafana-tui/releases/download/v0.2.0/grafana-tui_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "236a8060662ab074e351563de8c45aac4c7c2d77ca609fa874332938a0e7e711"

      define_method(:install) do
        bin.install "grafana-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lovromazgon/grafana-tui/releases/download/v0.2.0/grafana-tui_0.2.0_Darwin_arm64.tar.gz"
      sha256 "09b259918ef35843f074f001e7cce1d1f885b55ba20be367ebb3f6851a47351f"

      define_method(:install) do
        bin.install "grafana-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lovromazgon/grafana-tui/releases/download/v0.2.0/grafana-tui_0.2.0_Linux_x86_64.tar.gz"
      sha256 "21f0808108e12bdece2991621e20c6bb7f3bedd0ccf4be6eb451b94d86838024"
      define_method(:install) do
        bin.install "grafana-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lovromazgon/grafana-tui/releases/download/v0.2.0/grafana-tui_0.2.0_Linux_arm64.tar.gz"
      sha256 "9fddeeef7be1e4db135207f6598a9d0beb75d66bf34f9f3709750a5b74ab76d3"
      define_method(:install) do
        bin.install "grafana-tui"
      end
    end
  end

  test do
    assert_match(version.to_s, shell_output("#{bin}/grafana-tui --version"))
  end
end
