# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaTui < Formula
  desc ""
  homepage "https://github.com/lovromazgon/homebrew-tap"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lovromazgon/grafana-tui/releases/download/v0.1.0/grafana-tui_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "b0da0687341cf446bc50d1c02bf3ce5af49ccf72429fa3e0ed0a648eaba2ed12"

      define_method(:install) do
        bin.install "grafana-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lovromazgon/grafana-tui/releases/download/v0.1.0/grafana-tui_0.1.0_Darwin_arm64.tar.gz"
      sha256 "0d6c63f63bb3c2c7432d07b192d1de64dfb1987ba430c4f5d715143042cca12e"

      define_method(:install) do
        bin.install "grafana-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lovromazgon/grafana-tui/releases/download/v0.1.0/grafana-tui_0.1.0_Linux_x86_64.tar.gz"
      sha256 "0f6603a4ad2c94117e78c8f975e1808852c2b77ac90cc8783621cd939d506650"
      define_method(:install) do
        bin.install "grafana-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lovromazgon/grafana-tui/releases/download/v0.1.0/grafana-tui_0.1.0_Linux_arm64.tar.gz"
      sha256 "e53a72f5540e0f0e99dc6fba393ede57760f208e7d202f72bb5626dd2b91b915"
      define_method(:install) do
        bin.install "grafana-tui"
      end
    end
  end

  test do
    assert_match(version.to_s, shell_output("#{bin}/grafana-tui --version"))
  end
end
