# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Impromptu < Formula
  desc ""
  homepage "https://github.com/lovromazgon/homebrew-tap"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lovromazgon/impromptu/releases/download/v0.1.2/impromptu_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "540ca1fe2ba37201b984fc08265f489f6be88890534fa67914e5e22d92478ce0"

      def install
        bin.install "impromptu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lovromazgon/impromptu/releases/download/v0.1.2/impromptu_0.1.2_Darwin_arm64.tar.gz"
      sha256 "1315a31f930ae0180d699e5e8857a3abc2af21abd3e7cf3ff86a83995479f82b"

      def install
        bin.install "impromptu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lovromazgon/impromptu/releases/download/v0.1.2/impromptu_0.1.2_Linux_x86_64.tar.gz"
      sha256 "bff47a5219c5b9b27b6c7500af9a732a9ae46c85b87ce84066a7a9d8ca618b97"

      def install
        bin.install "impromptu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lovromazgon/impromptu/releases/download/v0.1.2/impromptu_0.1.2_Linux_arm64.tar.gz"
      sha256 "a9d063986341927f707571aa1ac0aa6657aad87fb5bee73f112e84a67ed7354e"

      def install
        bin.install "impromptu"
      end
    end
  end

  test do
    assert_match(version.to_s, shell_output("#{bin}/impromptu --version"))
  end
end
