# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Impromptu < Formula
  desc ""
  homepage "https://github.com/lovromazgon/homebrew-tap"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lovromazgon/impromptu/releases/download/v0.1.3/impromptu_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "04949a097881624547f5dd4078ce03c2e5fadec4d612a43998bb096a40acb2e0"

      def install
        bin.install "impromptu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lovromazgon/impromptu/releases/download/v0.1.3/impromptu_0.1.3_Darwin_arm64.tar.gz"
      sha256 "b4c94b22b65dffaf6784e2755b7437d9338453ec2fb84401a16d8c45622d7e13"

      def install
        bin.install "impromptu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lovromazgon/impromptu/releases/download/v0.1.3/impromptu_0.1.3_Linux_x86_64.tar.gz"
        sha256 "33a2f2df1039190eb217788d3d59ad4b0bcba298cfbd473fa62e0b095948552e"

        def install
          bin.install "impromptu"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lovromazgon/impromptu/releases/download/v0.1.3/impromptu_0.1.3_Linux_arm64.tar.gz"
        sha256 "d16c039e854124c51abfae177db12ac2f75b4156b2f14ae1df03399e5dc6a488"

        def install
          bin.install "impromptu"
        end
      end
    end
  end

  test do
    assert_match(version.to_s, shell_output("#{bin}/impromptu --version"))
  end
end
